Repository treolabs/treopim, pull requests merged in 2019-10, with the labels that each got.

#204 Fixed checking for changes before saving attributes
  client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Labels: feature

#203 Fix bugs
  app/Listeners/ProductImageController.php
  client/modules/pim/src/views/category/fields/image.js
  client/modules/pim/src/views/category/record/detail.js
  client/modules/pim/src/views/product/fields/image.js
  client/modules/pim/src/views/product/record/detail.js
Labels: bug

#206 Added Files Image type
  app/Repositories/PimImage.php
  app/Resources/i18n/de_DE/PimImage.json
  app/Resources/i18n/en_US/PimImage.json
  app/Resources/layouts/PimImage/detail.json
  app/Resources/layouts/PimImage/detailSmall.json
  app/Resources/metadata/clientDefs/PimImage.json
  app/Resources/metadata/entityDefs/PimImage.json
Labels: feature

#208 Fixed problem with select productImage
  app/Services/Product.php
Labels: bug

#210 Attribute image is not saving in Stream
  app/Listeners/ProductAttributeValueEntity.php
  app/Listeners/StreamController.php
  client/modules/pim/src/views/product-attribute-value/fields/value-container.js
  client/modules/pim/src/views/product-attribute-value/record/row-actions/relationship-no-unlink-in-product.js
Labels: bug

#211 Fix incorrect dispay of the images
  app/Resources/metadata/entityDefs/Product.json
  client/modules/pim/src/views/product/fields/image.js
  client/modules/pim/src/views/product/record/plate.js
Labels: bug

#213 Changes concerning "Add/Remove relations"
  app/Resources/metadata/entityDefs/Category.json
  app/Resources/metadata/entityDefs/PimImage.json
  app/Resources/metadata/entityDefs/Product.json
Labels: feature

#217 Optimization for category filter at Product list page
  app/SelectManagers/Product.php
Labels: feature

#226 Adaptation for new dragNdrop mechanic in list view
  app/Resources/metadata/clientDefs/AttributeGroup.json
  app/Resources/metadata/clientDefs/Category.json
  app/Resources/metadata/clientDefs/Product.json
  client/modules/pim/src/views/attribute-group/record/panels/attributes.js
Labels: feature

#236 Remove the product type "Package Product" and "Bundle Product". Add a new field to the entity "product".
  app/Controllers/Attribute.php
  app/Controllers/Product.php
  app/Controllers/ProductTypeBundle.php
  app/Controllers/ProductTypePackage.php
  app/Entities/ProductTypeBundle.php
  app/Entities/ProductTypePackage.php
  app/Migrations/V3Dot10Dot1.php
  app/Repositories/ProductTypeBundle.php
  app/Repositories/ProductTypePackage.php
  app/Resources/i18n/de_DE/MeasuringUnit.json
  app/Resources/i18n/de_DE/Product.json
  app/Resources/i18n/de_DE/ProductTypeBundle.json
  app/Resources/i18n/de_DE/ProductTypePackage.json
  app/Resources/i18n/en_US/MeasuringUnit.json
  app/Resources/i18n/en_US/Product.json
  app/Resources/i18n/en_US/ProductTypeBundle.json
  app/Resources/i18n/en_US/ProductTypePackage.json
  app/Resources/layouts/Product/detail.json
  app/Resources/layouts/Product/detailSmall.json
  app/Resources/layouts/Product/relationships.json
  app/Resources/metadata/clientDefs/Product.json
  app/Resources/metadata/entityDefs/MeasuringUnit.json
  app/Resources/metadata/entityDefs/Product.json
  app/Resources/metadata/entityDefs/ProductTypeBundle.json
  app/Resources/metadata/entityDefs/ProductTypePackage.json
  app/Resources/metadata/pim/productType.json
  app/Resources/metadata/scopes/ProductTypeBundle.json
  app/Resources/metadata/scopes/ProductTypePackage.json
  app/Resources/routes.json
  app/SelectManagers/Product.php
  app/Services/Attribute.php
  app/Services/Product.php
  app/Services/ProductTypeBundle.php
  app/Services/ProductTypePackage.php
  client/modules/pim/src/views/product/record/panels/item-in-products.js
  client/modules/pim/src/views/product/record/panels/product-bundles.js
  client/modules/pim/src/views/product/record/panels/product-packages.js
Labels: feature

#237 Displaying the main image
  app/Resources/metadata/clientDefs/PimImage.json
Labels: bug

#242 Fixed filters for attribute groups; added changing container for not visible element in showValidationMessage
  client/modules/pim/src/views/product/record/detail.js
  client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Labels: bug

#246 Added sorting ProductAttributeValue
  app/Resources/metadata/clientDefs/Product.json
Labels: bug

#245 Added trigger for collapsing panel
  client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Labels: bug

#252 Corrected sorting for attributeValues after update
  app/Resources/metadata/entityDefs/ProductAttributeValue.json
Labels: bug

#256 Fixed display of the decimal values
  app/Services/ProductAttributeValue.php
Labels: bug

#259 Added styles for enums values in product attribute values
  client/modules/pim/src/views/product-attribute-value/fields/value-container.js
Labels: bug

#258 Added display Image attribute in Stream
  app/Listeners/ProductAttributeValueEntity.php
  app/Services/RevisionField.php
  client/modules/pim/src/views/product-attribute-value/record/row-actions/relationship-no-unlink-in-product.js
Labels: feature

#260 Fixed arrow
  client/modules/pim/res/templates/attribute/fields/type-value/edit.tpl
  client/modules/pim/src/views/attribute/fields/type-value.js
Labels: bug

#262 Removed quickCreate for Channel; fixed product attribute value displaying
  app/Resources/metadata/clientDefs/Channel.json
  client/modules/pim/src/views/product-attribute-value/fields/value-container.js
Labels: bug, feature

#264 Fixed listeners in Product Attribute Values panel
  app/Resources/metadata/clientDefs/Product.json
  client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Labels: bug

#266 Adapted to the Core 3.24 and the module DAM
  app/Resources/i18n/de_DE/Global.json
  app/Resources/i18n/en_US/Global.json
  app/Resources/layouts/AssetRelation/detailSmall.json
  app/Resources/metadata/clientDefs/AssetRelation.json
  app/Resources/metadata/clientDefs/Product.json
  app/Resources/metadata/entityDefs/Asset.json
  app/Resources/metadata/entityDefs/AssetRelation.json
  app/Resources/metadata/entityDefs/Channel.json
  app/Resources/metadata/entityDefs/Product.json
  app/Services/Attachment.php
  composer.json
Labels: feature

#267 Fixed default layout Bottom Panels
  app/Resources/i18n/de_DE/Global.json
  app/Resources/i18n/en_US/Global.json
  app/Resources/layouts/Product/relationships.json
Labels: bug
