Repository treolabs/treopim, pull requests merged in 2019-12, with the labels that each got.

#340 Active for Channel default is false
  app/Resources/metadata/entityDefs/Channel.json
  app/Resources/metadata/entityDefs/Product.json
Labels: feature

#343 Fixed filters with catalog tree panel
  client/modules/pim/src/views/product/list.js
  client/modules/pim/src/views/product/record/search.js
Labels: bug

#349 Fixed filters with catalog tree panel
  client/modules/pim/src/views/product/list.js
  client/modules/pim/src/views/product/record/search.js
Labels: bug

#359 79918
  app/Services/ProductAttributeValue.php
Labels: feature

#358 Set default value in isActive for channel after deleted link
  app/Listeners/ChannelEntity.php
  app/Listeners/ProductEntity.php
  app/Services/Channel.php
Labels: bug

#365 Filter products by category regardless of Scope
  app/SelectManagers/Product.php
Labels: bug

#378 added importing unit attributes
  app/Import/Types/Simple/FieldConverters/Unit.php
  app/Import/Types/Simple/Handlers/ProductHandler.php
  app/Resources/i18n/de_DE/Global.json
  app/Resources/i18n/en_US/Global.json
  app/Resources/metadata/import/simple.json
Labels: feature

#377 Added method for changing mode in isActive field
  client/modules/pim/src/views/channel/record/list-in-product.js
Labels: feature

#381 Adaptation for Multi-Language 1.14
  client/modules/pim/src/views/product-attribute-value/fields/value-container.js
  client/modules/pim/src/views/product-attribute-value/record/detail.js
  client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Labels: feature

#386 Changed columns width
  app/Resources/layouts/ProductAttributeValue/listSmall.json
Labels: feature

#387 Fixed bugs in migration
  app/Migrations/V3Dot10Dot0.php
Labels: bug

#388 Remove productPrices
  app/Resources/i18n/de_DE/ChannelPricing.json
  app/Resources/layouts/Product/relationships.json
Labels: bug

#391 80100
  app/Migrations/V3Dot12Dot0.php
Labels: enhancement

#392 Fixed Generic Fields filter
  client/modules/pim/src/views/product/record/detail.js
Labels: bug

#393 T 80100
  app/Listeners/CatalogEntity.php
  app/Module.php
  app/Repositories/Attribute.php
  app/Repositories/Catalog.php
  app/Repositories/PimImage.php
  app/Repositories/ProductCategory.php
  app/Resources/i18n/de_DE/Category.json
  app/Resources/i18n/de_DE/ProductCategory.json
  app/Resources/i18n/en_US/Category.json
  app/Resources/i18n/en_US/ProductCategory.json
  app/Resources/layouts/AssetRelation/detailSmall.json
  app/Resources/layouts/ProductCategory/detailSmall.json
  app/Resources/metadata/clientDefs/AssetRelation.json
  app/Resources/metadata/entityDefs/Asset.json
  app/Resources/metadata/entityDefs/AssetRelation.json
  app/Resources/metadata/entityDefs/Channel.json
  app/Resources/metadata/entityDefs/ProductCategory.json
  client/modules/pim/src/views/product/record/detail.js
  composer.json
Labels: feature

#396 Fixed migration mainImage and channels for Product and Category
  app/Migrations/V3Dot10Dot0.php
Labels: bug

#397 Fixed migration for pimImages to down
  app/Migrations/V3Dot10Dot0.php
Labels: bug

#399 Fixed validation error while creating multi-lang attribute of type Enum or Multi-Enum;
  app/Module.php
Labels: bug

#400 Fixed validation multilang ProductAttrivuteValue
  app/Module.php
Labels: bug

#401 T 80100
  app/Event.php
  app/Listeners/LayoutController.php
  app/Migrations/V3Dot12Dot0.php
  app/Services/Attachment.php
Labels: bug

#402 80100
  app/Migrations/V3Dot12Dot0.php
Labels: bug

#403 80100
  app/Migrations/V3Dot12Dot0.php
Labels: bug

#404 80100
  app/Migrations/V3Dot12Dot0.php
Labels: bug

#407 Deleted Pim\Service\Attachment
  app/Services/Attachment.php
  client/modules/pim/src/views/product/record/detail.js
Labels: bug

#408 Corrected displaying of product categories panel
  app/Resources/metadata/clientDefs/Product.json
  client/modules/pim/src/views/product/record/panels/product-categories.js
Labels: bug
